export const products = [
  {
    id: 1,
    slug: "smartphone-pro-x",
    name: "Smartphone Pro X",
    category: "Électronique",
    price: 899.99,
    rating: 4.6,
    stock: 25,
    image: "https://picsum.photos/seed/smartphone-pro-x/600/400",
    description: "Smartphone haut de gamme avec écran OLED, triple capteur photo et charge rapide.",
    features: ["Écran OLED 6.5\"", "128 Go de stockage", "Triple capteur photo", "Charge rapide 65W"],
  },
  {
    id: 2,
    slug: "laptop-ultrabook-15",
    name: "Laptop Ultrabook 15",
    category: "Électronique",
    price: 1299.0,
    rating: 4.4,
    stock: 12,
    image: "https://picsum.photos/seed/laptop-ultrabook-15/600/400",
    description: "Ultrabook léger et puissant, idéal pour le travail nomade.",
    features: ["Écran 15\" Full HD", "16 Go RAM", "SSD 512 Go", "Autonomie 12h"],
  },
  {
    id: 3,
    slug: "casque-audio-sans-fil",
    name: "Casque Audio Sans Fil",
    category: "Accessoires",
    price: 149.99,
    rating: 4.7,
    stock: 60,
    image: "https://picsum.photos/seed/casque-audio-sans-fil/600/400",
    description: "Casque Bluetooth à réduction de bruit active.",
    features: ["Réduction de bruit active", "Autonomie 30h", "Bluetooth 5.3", "Micro intégré"],
  },
  {
    id: 4,
    slug: "montre-connectee-sport",
    name: "Montre Connectée Sport",
    category: "Accessoires",
    price: 199.99,
    rating: 4.1,
    stock: 40,
    image: "https://picsum.photos/seed/montre-connectee-sport/600/400",
    description: "Montre connectée avec GPS intégré, capteur cardio, 100+ modes sport et étanche 50m.",
    features: ["GPS intégré", "Cardiofréquencemètre", "Étanche 50m", "Autonomie 14 jours"],
  },
  {
    id: 5,
    slug: "enceinte-bluetooth-portable",
    name: "Enceinte Bluetooth Portable",
    category: "Accessoires",
    price: 79.99,
    rating: 4.3,
    stock: 55,
    image: "https://picsum.photos/seed/enceinte-bluetooth-portable/600/400",
    description: "Enceinte portable étanche avec un son puissant.",
    features: ["Étanche IPX7", "Autonomie 20h", "Bluetooth 5.0", "Basses renforcées"],
  },
  {
    id: 6,
    slug: "clavier-mecanique-rgb",
    name: "Clavier Mécanique RGB",
    category: "Informatique",
    price: 119.99,
    rating: 4.5,
    stock: 30,
    image: "https://picsum.photos/seed/clavier-mecanique-rgb/600/400",
    description: "Clavier mécanique gaming avec rétroéclairage RGB personnalisable.",
    features: ["Switches mécaniques", "Rétroéclairage RGB", "Anti-ghosting", "Repose-poignet"],
  },
  {
    id: 7,
    slug: "souris-gaming-sans-fil",
    name: "Souris Gaming Sans Fil",
    category: "Informatique",
    price: 69.99,
    rating: 4.4,
    stock: 45,
    image: "https://picsum.photos/seed/souris-gaming-sans-fil/600/400",
    description: "Souris gaming ultra-légère avec capteur haute précision.",
    features: ["Capteur 26000 DPI", "Sans fil 2.4GHz", "8 boutons programmables", "Autonomie 70h"],
  },
  {
    id: 8,
    slug: "ecran-4k-27-pouces",
    name: "Écran 4K 27 pouces",
    category: "Informatique",
    price: 349.99,
    rating: 4.6,
    stock: 18,
    image: "https://picsum.photos/seed/ecran-4k-27-pouces/600/400",
    description: "Moniteur 4K IPS avec des couleurs fidèles et une fréquence de 144Hz.",
    features: ["Résolution 4K UHD", "144Hz", "Dalle IPS", "Compatible HDR10"],
  },
  {
    id: 9,
    slug: "sac-a-dos-ordinateur",
    name: "Sac à Dos Ordinateur",
    category: "Accessoires",
    price: 49.99,
    rating: 4.2,
    stock: 70,
    image: "https://picsum.photos/seed/sac-a-dos-ordinateur/600/400",
    description: "Sac à dos résistant à l'eau avec compartiment rembourré pour ordinateur portable.",
    features: ["Compartiment 15.6\"", "Résistant à l'eau", "Port USB de charge", "Dos aéré"],
  },
  {
    id: 10,
    slug: "chargeur-rapide-usb-c",
    name: "Chargeur Rapide USB-C",
    category: "Accessoires",
    price: 29.99,
    rating: 4.5,
    stock: 90,
    image: "https://picsum.photos/seed/chargeur-rapide-usb-c/600/400",
    description: "Chargeur USB-C 65W compatible avec la majorité des appareils modernes.",
    features: ["Puissance 65W", "USB-C PD", "Compact", "Protection surchauffe"],
  },
];
